### ISSUE TITLE
Reuse seed not working with StylePile

### ISSUE THREAD

**Issue by matrix4767** [some9000/StylePile#11]
When this script is enabled, the random seed used won't appear when clicking the reuse seed button. Nor will it show up if temporarily disabling the script. You'd have to generate something without stylepile to get the seed back.

**Comment by some9000** [comment]
Ok, I will look into it. This whole interface stuff is quite weird and sort-of barely documented. So it's a lot of trial and error.

**Comment by some9000** [comment]
This should be fixed in the latest version. For the image info to properly show for each image this needs to be added to your SD one way or another: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4899
