### ISSUE TITLE
BUG? Why are StylePile controls grayed out?

### ISSUE THREAD

**Issue by Duemellon** [some9000/StylePile#14]
Even when I have StylePile selected the controls aren't enabled. Am I missing something? 

![image](https://user-images.githubusercontent.com/113479041/199733631-bf2e682c-5ee4-4c4c-b4d7-2a304596c107.png)

**Comment by some9000** [comment]
That does seem weird... Some sort of a conflict with some other script? What happens if you leave it as the only script in scripts folder?

**Comment by Duemellon** [comment]
Here are my current scripts:
![image](https://user-images.githubusercontent.com/113479041/199750920-9a564da2-bcf6-4e5c-ad3d-08651f21727b.png)
 
Running now with only StylePile in scripts... let's see...

**Comment by Duemellon** [comment]
Tried Firefox, same result but not "Grayed"

**Comment by some9000** [comment]
That's weird... Not sure from your screenshot, is the StylePile folder with the images in script folder as well?

**Comment by Duemellon** [comment]
no. It is not. I didn't have it in there last time before the upgrade

**Comment by Duemellon** [comment]
** before the latest StylePile upgrade

I'm looking for this "pictures" stuff now to add it.

**Comment by some9000** [comment]
Perhaps just try extracting all the files from the latest version into the scripts folder? I suspect missing images may be causing the problems.

**Comment by Duemellon** [comment]
yes. Now it's working with the image folder there. Is there a way to include a warning message about it? Most Scripts don't need additional folders. I see it in your Readme when looking harder but honestly I just skimmed it when installing. 

Thanks for the help.
