### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by danzelus** [some9000/StylePile#15]
add examples for other types (image types, colors, etc.). That would be great )

**Comment by some9000** [comment]
Working on it. It's just the interface system gradio loads all the images into the page (you may have seen it loading like a 80Mb page into address bar) so I'm looking into doing that in some other way. Better examples (and even more artists hand picked by me) are coming in general:
![Bo Bartlett](https://user-images.githubusercontent.com/17021558/200157420-0da576f0-09b3-4f7c-a101-79bca793a9e5.jpg)
![Barbara Kruger](https://user-images.githubusercontent.com/17021558/200157427-0135fc3b-ffaa-401e-afdf-962312a93ff5.jpg)
![Todd McFarlane](https://user-images.githubusercontent.com/17021558/200157437-1ed2bc77-deec-4363-ab9a-b8f581968edc.jpg)
![Victo Ngai](https://user-images.githubusercontent.com/17021558/200157461-691e4e62-a07c-40ab-b901-93cab6757ceb.jpg)

**Comment by Kylescher1** [comment]
seems to be broken

**Comment by some9000** [comment]
> seems to be broken 
> 

If you are trying beta then it's disabled, because the larger images make everything load longer. I'm looking for a way to implement this better.

**Comment by some9000** [comment]
For now you can use this: https://imgur.com/a/8QVTP0E
