### ISSUE TITLE
When enabling Stylepile it disables features in Automatic1111

### ISSUE THREAD

**Issue by jasoncharles** [some9000/StylePile#19]
Hi, thanks very much for this script it is the best. 
When I enable the script in Automatic1111 and generate a picture the prompt info does not appear under the generated picture, and I am unable to select the seed recall button. When I do not select this script, I do not get this issue. I have tried other built in Automatic1111 scripts, and they do not produce this issue.

Thanks

**Comment by some9000** [comment]
Hi! I am aware of that and it seems to be somewhat related to sending multiple commands. Have been looking into fixing it, but the docs are fairly obscure, so it just feels like endless experimentation. But it's on a todo list for sure.

**Comment by some9000** [comment]
This should be fixed in the latest version. For the image info to properly show for each image this needs to be added to your SD one way or another: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4899
