### ISSUE TITLE
No info when run with random option

### ISSUE THREAD

**Issue by Rogal80** [some9000/StylePile#20]
Hi, this is a cool add-on. It would be even better if you chose "Random All" and all the information was saved with the proper tag. Right now, it is showing (:0.1) .This will give us the ability to check combination when using generate forever.

now is like this 
![obraz](https://user-images.githubusercontent.com/112553453/201208787-8cf5d25f-01fd-48c1-afd4-e6fa13b4a26e.png)
 nice to have
 ![obraz](https://user-images.githubusercontent.com/112553453/201209033-29920c5b-6931-4b5c-b3bd-b9aeb84963c3.png)

**Comment by some9000** [comment]
Oh, that looks weird. I'll check it out. Must be typo on my part.

**Comment by some9000** [comment]
This should be fixed in the latest version. For the image info to properly show for each image this needs to be added to your SD one way or another: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4899
