### ISSUE TITLE
ResourceDir error

### ISSUE THREAD

**Issue by jstenner** [some9000/StylePile#24]
In the current version the script loads but none of the interface items are selectable (see image). The script throws an error that it cannot find resources. 
![IMG_4093](https://user-images.githubusercontent.com/3853555/203636752-89add4b9-1968-4ad1-8f61-af138ad73d17.png)

Line 370 currently:
ResourceDir = os.path.join(file_dir,f"extensions/StylePile/StylePile/")

It should be:
ResourceDir = os.path.join(file_dir,f"scripts/StylePile/")

HTH

**Comment by Kilvoctu** [comment]
I'm not sure, but I think the intended branch to use is the [beta branch](https://github.com/some9000/StylePile/tree/Beta-2.0).

This script is an extension now, so you want to install it through the web ui, under extensions (and also delete it from your scripts folder)
![image](https://user-images.githubusercontent.com/2993060/203668562-745ceb12-5762-43a5-8222-c1e713f2870d.png)

Then after that, restarting ui, it should work
![image](https://user-images.githubusercontent.com/2993060/203668624-86b4ff53-fde2-4ef9-9d0b-054d048ce7dc.png)
![image](https://user-images.githubusercontent.com/2993060/203668398-c777e04a-a0f0-41ec-b9ff-96974cca0c09.png)

**Comment by some9000** [comment]
Yeah, sorry, it became a tiny little bit of a mess getting some lines from the beta paths into current version. I'll do my best to update the instructions and, most likely, move current beta as release soon. Docs is really the hardest part... 🙃

**Comment by Kilvoctu** [comment]
> Docs is really the hardest part... 🙃

For sure. On my project I have like 50 readme updates over these past 6 weeks, and I started moving information into a wiki.  
I started making PR for any features or changes (~30 PRs now) and try to thoroughly document what the PR is, process I'm doing for it, etc. And there's tons of comments in my code.

It does pay off though. It helps others, but especially current and future you, understand what's going on.

**Comment by some9000** [comment]
Yeah, from that point of view my GitHub activity is a total mess. Trying to comment code in general, but will add more. So it's easier for any contributors to understand what's happening. Then again the script itself is reasonably simple, just looks big because of the arrays and UI elements.

Either way, it feels like this latest version has a solid batch of functions so, in theory, finalizing the manual should be doable. We'll see.

**Comment by jstenner** [comment]
Cool, thanks. Glad to see it as an extension now!
