### ISSUE TITLE
Error when setting third Art Movement drop down

### ISSUE THREAD

**Issue by freecoderwaifu** [some9000/StylePile#28]
Great work with script and now the extension, just found a small bug when setting the third Art movement dropdown. It only happens with that specific dropdown, when setting it to any selection except "Not set". All other dropdowns work as intended, even when all of them are set to a specific selection or Random they all work as expected. Setting the last Art movement dropdown prevents all other dropdowns from working. 

Here's the console log: 

`Error completing request
Arguments: ('test', 'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name', 'None', 'None', 35, 5, False, False, 1, 1, 10, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 5, 0, 0, 0, 0, 0.25, True, True, False, True, False, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, 0, False, False, False, '', 'Illustration', 'svg', True, True, False, 0.5, True, 16, True, 16, 1, '', 0, '', True, False, False, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Australian Tonalism', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', '', 'None', 30, 4, 0, 0, False, 'None', '<br>', 'None', 30, 4, 0, 0, 4, 0.4, True, 32, '', 5, 24, 12.5, 1000, 'DDIM', 0, 64, 64, '', 64, 7.5, 0.42, 'DDIM', 64, 64, 1, 0, 92, True, True, True, False, False, False, 4.0, '', 10.0, False, False, True, 30.0, True, False, False, 0, 0.0, 10.0, True, 30.0, True, '{inspiration}', None) {}
Traceback (most recent call last):
  File "F:\voldy\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\voldy\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "F:\voldy\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "F:\voldy\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "F:\voldy\stable-diffusion-webui\extensions\StylePile\scripts\StylePile.py", line 547, in run
    if ArtMovements[selArtMovementC] == "Random":
TypeError: list indices must be integers or slices, not str`

**Comment by some9000** [comment]
Thanks for the heads up! This has been fixed now. Should be smooth sailing from here. If you have any other feedback/ideas feel free to share.
