### ISSUE TITLE
Random Elements Only Selected Once Per Prompt

### ISSUE THREAD

**Issue by soarkyfluffbutt** [some9000/StylePile#30]
Ex.: "A woman wearing a [A], [A]" updates to "A woman wearing a jacket, jacket" for generation, NOT the expected result of two separate random choices. 

If this is the intended use then I don't see much reason to use the random sections instead of the X and Y sequences.

**Comment by some9000** [comment]
Well, here's the thing - if those are truly random then there's a chance of duplicates anyway. This is why there are three fields so you can try to "expand" the potential randomness. The way I mostly use it "A woman wearing a [A], [B]" with A being "Red,Yellow,Blue,Cyan" and B being "Jacket,Hoodie,Coat" for example. And [X],[Y] is also a decent approach.

If the random elements attempt to not repeat then it's basically just a shifted cycle. Like, what do we do when the amount of [A]s used in the prompt is above total values? Hence how it works now.

**Comment by some9000** [comment]
To somewhat help with this I have added three more random fields in the next version. So six total. In theory that should be quite enough for most cases. And, if not, you can just use multiple lines and StylePile will automatically go through those which lets you have waaay more variety.
