### ISSUE TITLE
Reuse seed button not working

### ISSUE THREAD

**Issue by jasoncharles** [some9000/StylePile#32]
Hi, 
I have updated to the latest extension version of StylePile, but when I activate the script and generate an image the "Reuse seed" button still does not work.

Thanks
Jason

**Comment by some9000** [comment]
Ok, I'll look into it. Perhaps it is related to how it functions with batches. Will need to do some testing.

At least the descriptions under selected images are correct now so it's easier to just copy the seed.

**Comment by some9000** [comment]
This has been completely fixed in the upcoming version.
