### ISSUE TITLE
StylePile creating tons of images in \AppData\Local\Temp

### ISSUE THREAD

**Issue by Zyin055** [some9000/StylePile#37]
So I was using a program called WizTree to help clean up some space on my hard drive. To my surprise, I found that there were 797 folders in C:\Users\<user>\AppData\Local\Temp that had exactly 78.4MB of files. Each folder contained the exact same contents - the set of images used to show StylePile's author styles, such as Adam Hughesm17qy1g6.jpg, Adi Granov7x29rdrt.jpg, Adolf Kosarekbywzcl1n.jpg, ..., Zdzislaw Beksinski5c9tu9yp.jpg.

This is taking up 62GB of storage.

WizTree screenshot #1: https://imgur.com/a/VMfPhmK

Further inspection revealed even more images with folders of size 20.6MB with images with names like Kinetic Pointillism0ketvc_u.jpg.

WizTree screenshot #2: https://imgur.com/a/MDrzZ6v

**Comment by jwvanderbeck** [comment]
It isn't StylePile directly I think.  Its A1111.  I have a crapton of images in my temp that show up from the main webui and every plugin for it.

**Comment by some9000** [comment]
Sorry for the super late reply. Yeah, I suspect it has to do with A1111. Since we are just placing images in the standard extensions folder and not even expecting it to make any copies. If this continues a post on their forum ir probably in order.
