### ISSUE TITLE
Seed increment bug, generate duplicates

### ISSUE THREAD

**Issue by NeiroNext** [some9000/StylePile#44]
A very interesting extension. But unfortunately I noticed a bug, the script somehow breaks the generation of several images. If you set the start seed, then for some reason the increment is not performed, which is why the same image is generated.
![image](https://user-images.githubusercontent.com/8338488/218005875-ff179026-62ed-48bc-a02d-e9e9bb93a50a.png)

**Comment by some9000** [comment]
This is actually on purpose - seed will increase if you change **Batch size**. The checkbox says that: Increase seed with batch size
Reason: So you can do batches of changing prompts that keep the same seed increase. Basically, as an example you set Batch size to 4 and Batch count to 2. This means that you will get 1,2,3,4,1,2,3,4 with different prompts if you entered several as [X] and added that to the main prompt.
I may have to document this better (or at all, at the moment...)
