### ISSUE TITLE
Add custom entries?

### ISSUE THREAD

**Issue by jwvanderbeck** [some9000/StylePile#45]
Is there some way to add custom entries, like say I want to add a custom artist? I would like to add "Annie Leibovitz" to StylePile so I can quickly select it when I want because I can never remember hot to spell her name :)

**Comment by some9000** [comment]
Hi! Sorry for the lateness. Will have a closer look at your other questions later, but as for this one:
StylePile uses images in its subfolders to create the dropdowns. So you can jus throw images into extensions\StylePile\StylePile\Artists and their name will be used for artist name selection. This also means you can throw out any artists you don't ever want to see in random picks etc. Same goes for other images in those subfolders.
