### ISSUE TITLE
More specific prompts

### ISSUE THREAD

**Issue by dicedblob** [some9000/StylePile#7]
Take "Monsters" for example. As it is, it would be rather difficult to generate coherent monsters without missing or extra limbs.

Or "Robots", containing "oil on canvas".

What I'm trying to say is: keep thematic prompts free from non-thematic influences. I believe in the long run, when this will grow, it would be beneficial to be specific rather than general. Otherwise the results might quickly become overloaded.

**Comment by some9000** [comment]
Thanks for the comment.
For now those are mostly for testing purposes. I am hoping to add the ability to easily edit them in the future. But, also, in the next version those will be quite cleaned up and the approach to results in general has been improved quite a bit. Hoping to release it reasonably soon, but it seems the latest AUTOMATIC1111 update broke certain things I used to improve the interface.

**Comment by dicedblob** [comment]
Very much looking forward to it. <3

**Comment by some9000** [comment]
This will be fixed and improved quite a bit in the upcoming version. Not really sure when it will come out since it basically demands a full rewrite of the manual and some cleanup work. But it will be there.
