### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by JustAnOkapi** [some9000/StylePile#9]
Allow to make a grid with check boxes

**Comment by some9000** [comment]
You mean like mix and match styles and artists? With checkboxes or such? Have been thinking about it, but it's a little above my Python coding skills at the moment. Also not sure if it wouldn't make things too complicated.
But will look into it and do some testing.

**Comment by freecoderwaifu** [comment]
Seconding this, tried the beta and the extra styles and artists are nice, would be great to be able to combine multiple of them.

**Comment by some9000** [comment]
You can try current beta for my implementation of something like this. It's limited to picking up to 3 artists, but that already seems quite enough.

Combined with random selections there's quite a bit of variety that can be achieved. It's not documented yet, but tips should get you started.
